package dvonn


func connectCells(cells map[string]*HexNode) {

	cells["a1"].SetChildNode(BOTTON_EDGE, cells["b1"])
	cells["a1"].SetChildNode(RIGHTUPPER_EDGE, cells["a2"])
	cells["a1"].SetChildNode(RIGHTBOTTON_EDGE, cells["b2"])

	cells["a2"].SetChildNode(LEFTBOTTON_EDGE, cells["a1"])
	cells["a2"].SetChildNode(BOTTON_EDGE, cells["b2"])
	cells["a2"].SetChildNode(RIGHTBOTTON_EDGE, cells["b3"])
	cells["a2"].SetChildNode(RIGHTUPPER_EDGE, cells["a3"])

	cells["a3"].SetChildNode(LEFTBOTTON_EDGE, cells["a2"])
	cells["a3"].SetChildNode(BOTTON_EDGE, cells["b3"])
	cells["a3"].SetChildNode(RIGHTBOTTON_EDGE, cells["b4"])

	cells["b1"].SetChildNode(UPPER_EDGE, cells["a1"])
	cells["b1"].SetChildNode(RIGHTUPPER_EDGE, cells["b2"])
	cells["b1"].SetChildNode(RIGHTBOTTON_EDGE, cells["c2"])
	cells["b1"].SetChildNode(BOTTON_EDGE, cells["c1"])

	cells["b2"].SetChildNode(UPPER_EDGE, cells["a2"])
	cells["b2"].SetChildNode(RIGHTUPPER_EDGE, cells["b3"])
	cells["b2"].SetChildNode(RIGHTBOTTON_EDGE, cells["c3"])
	cells["b2"].SetChildNode(BOTTON_EDGE, cells["c2"])
	cells["b2"].SetChildNode(LEFTBOTTON_EDGE, cells["b1"])
	cells["b2"].SetChildNode(LEFTUPPER_EDGE, cells["a1"])

	cells["b3"].SetChildNode(UPPER_EDGE, cells["a3"])
	cells["b3"].SetChildNode(RIGHTUPPER_EDGE, cells["b4"])
	cells["b3"].SetChildNode(RIGHTBOTTON_EDGE, cells["c4"])
	cells["b3"].SetChildNode(BOTTON_EDGE, cells["c3"])
	cells["b3"].SetChildNode(LEFTBOTTON_EDGE, cells["b2"])
	cells["b3"].SetChildNode(LEFTUPPER_EDGE, cells["a2"])

	cells["b4"].SetChildNode(RIGHTBOTTON_EDGE, cells["c5"])
	cells["b4"].SetChildNode(BOTTON_EDGE, cells["c4"])
	cells["b4"].SetChildNode(LEFTBOTTON_EDGE, cells["b3"])
	cells["b4"].SetChildNode(LEFTUPPER_EDGE, cells["a3"])

	cells["c1"].SetChildNode(UPPER_EDGE, cells["b1"])
	cells["c1"].SetChildNode(RIGHTUPPER_EDGE, cells["c2"])
	cells["c1"].SetChildNode(RIGHTBOTTON_EDGE, cells["d2"])
	cells["c1"].SetChildNode(BOTTON_EDGE, cells["d1"])

	cells["c2"].SetChildNode(UPPER_EDGE, cells["b2"])
	cells["c2"].SetChildNode(RIGHTUPPER_EDGE, cells["c3"])
	cells["c2"].SetChildNode(RIGHTBOTTON_EDGE, cells["d3"])
	cells["c2"].SetChildNode(BOTTON_EDGE, cells["d2"])
	cells["c2"].SetChildNode(LEFTBOTTON_EDGE, cells["c1"])
	cells["c2"].SetChildNode(LEFTUPPER_EDGE, cells["b1"])

	cells["c3"].SetChildNode(UPPER_EDGE, cells["b3"])
	cells["c3"].SetChildNode(RIGHTUPPER_EDGE, cells["c4"])
	cells["c3"].SetChildNode(RIGHTBOTTON_EDGE, cells["d4"])
	cells["c3"].SetChildNode(BOTTON_EDGE, cells["d3"])
	cells["c3"].SetChildNode(LEFTBOTTON_EDGE, cells["c2"])
	cells["c3"].SetChildNode(LEFTUPPER_EDGE, cells["b2"])

	cells["c4"].SetChildNode(UPPER_EDGE, cells["b4"])
	cells["c4"].SetChildNode(RIGHTUPPER_EDGE, cells["c5"])
	cells["c4"].SetChildNode(RIGHTBOTTON_EDGE, cells["d5"])
	cells["c4"].SetChildNode(BOTTON_EDGE, cells["d4"])
	cells["c4"].SetChildNode(LEFTBOTTON_EDGE, cells["c3"])
	cells["c4"].SetChildNode(LEFTUPPER_EDGE, cells["b3"])

	cells["c5"].SetChildNode(BOTTON_EDGE, cells["d5"])
	cells["c5"].SetChildNode(LEFTBOTTON_EDGE, cells["c4"])
	cells["c5"].SetChildNode(LEFTUPPER_EDGE, cells["b4"])


	cells["d1"].SetChildNode(UPPER_EDGE, cells["c1"])
	cells["d1"].SetChildNode(RIGHTUPPER_EDGE, cells["d2"])
	cells["d1"].SetChildNode(RIGHTBOTTON_EDGE, cells["e2"])
	cells["d1"].SetChildNode(BOTTON_EDGE, cells["e1"])

	cells["d2"].SetChildNode(UPPER_EDGE, cells["c2"])
	cells["d2"].SetChildNode(RIGHTUPPER_EDGE, cells["d3"])
	cells["d2"].SetChildNode(RIGHTBOTTON_EDGE, cells["e3"])
	cells["d2"].SetChildNode(BOTTON_EDGE, cells["e2"])
	cells["d2"].SetChildNode(LEFTBOTTON_EDGE, cells["d1"])
	cells["d2"].SetChildNode(LEFTUPPER_EDGE, cells["c1"])

	cells["d3"].SetChildNode(UPPER_EDGE, cells["c3"])
	cells["d3"].SetChildNode(RIGHTUPPER_EDGE, cells["d4"])
	cells["d3"].SetChildNode(RIGHTBOTTON_EDGE, cells["e4"])
	cells["d3"].SetChildNode(BOTTON_EDGE, cells["e3"])
	cells["d3"].SetChildNode(LEFTBOTTON_EDGE, cells["d2"])
	cells["d3"].SetChildNode(LEFTUPPER_EDGE, cells["c2"])

	cells["d4"].SetChildNode(UPPER_EDGE, cells["c4"])
	cells["d4"].SetChildNode(RIGHTUPPER_EDGE, cells["d5"])
	cells["d4"].SetChildNode(RIGHTBOTTON_EDGE, cells["e5"])
	cells["d4"].SetChildNode(BOTTON_EDGE, cells["e4"])
	cells["d4"].SetChildNode(LEFTBOTTON_EDGE, cells["d3"])
	cells["d4"].SetChildNode(LEFTUPPER_EDGE, cells["c3"])

	cells["d5"].SetChildNode(UPPER_EDGE, cells["c5"])
	cells["d5"].SetChildNode(BOTTON_EDGE, cells["e5"])
	cells["d5"].SetChildNode(LEFTBOTTON_EDGE, cells["d4"])
	cells["d5"].SetChildNode(LEFTUPPER_EDGE, cells["c4"])

	cells["e1"].SetChildNode(UPPER_EDGE, cells["d1"])
	cells["e1"].SetChildNode(RIGHTUPPER_EDGE, cells["e2"])
	cells["e1"].SetChildNode(RIGHTBOTTON_EDGE, cells["f2"])
	cells["e1"].SetChildNode(BOTTON_EDGE, cells["f1"])

	cells["e2"].SetChildNode(UPPER_EDGE, cells["d2"])
	cells["e2"].SetChildNode(RIGHTUPPER_EDGE, cells["e3"])
	cells["e2"].SetChildNode(RIGHTBOTTON_EDGE, cells["f3"])
	cells["e2"].SetChildNode(BOTTON_EDGE, cells["f2"])
	cells["e2"].SetChildNode(LEFTBOTTON_EDGE, cells["e1"])
	cells["e2"].SetChildNode(LEFTUPPER_EDGE, cells["d1"])

	cells["e3"].SetChildNode(UPPER_EDGE, cells["d3"])
	cells["e3"].SetChildNode(RIGHTUPPER_EDGE, cells["e4"])
	cells["e3"].SetChildNode(RIGHTBOTTON_EDGE, cells["f4"])
	cells["e3"].SetChildNode(BOTTON_EDGE, cells["f3"])
	cells["e3"].SetChildNode(LEFTBOTTON_EDGE, cells["e2"])
	cells["e3"].SetChildNode(LEFTUPPER_EDGE, cells["d2"])

	cells["e4"].SetChildNode(UPPER_EDGE, cells["d4"])
	cells["e4"].SetChildNode(RIGHTUPPER_EDGE, cells["e5"])
	cells["e4"].SetChildNode(RIGHTBOTTON_EDGE, cells["f5"])
	cells["e4"].SetChildNode(BOTTON_EDGE, cells["f4"])
	cells["e4"].SetChildNode(LEFTBOTTON_EDGE, cells["e3"])
	cells["e4"].SetChildNode(LEFTUPPER_EDGE, cells["d3"])

	cells["e5"].SetChildNode(UPPER_EDGE, cells["d5"])
	cells["e5"].SetChildNode(BOTTON_EDGE, cells["f5"])
	cells["e5"].SetChildNode(LEFTBOTTON_EDGE, cells["e4"])
	cells["e5"].SetChildNode(LEFTUPPER_EDGE, cells["d4"])


	cells["f1"].SetChildNode(UPPER_EDGE, cells["e1"])
	cells["f1"].SetChildNode(RIGHTUPPER_EDGE, cells["f2"])
	cells["f1"].SetChildNode(RIGHTBOTTON_EDGE, cells["g2"])
	cells["f1"].SetChildNode(BOTTON_EDGE, cells["g1"])

	cells["f2"].SetChildNode(UPPER_EDGE, cells["e2"])
	cells["f2"].SetChildNode(RIGHTUPPER_EDGE, cells["f3"])
	cells["f2"].SetChildNode(RIGHTBOTTON_EDGE, cells["g3"])
	cells["f2"].SetChildNode(BOTTON_EDGE, cells["g2"])
	cells["f2"].SetChildNode(LEFTBOTTON_EDGE, cells["f1"])
	cells["f2"].SetChildNode(LEFTUPPER_EDGE, cells["e1"])

	cells["f3"].SetChildNode(UPPER_EDGE, cells["e3"])
	cells["f3"].SetChildNode(RIGHTUPPER_EDGE, cells["f4"])
	cells["f3"].SetChildNode(RIGHTBOTTON_EDGE, cells["g4"])
	cells["f3"].SetChildNode(BOTTON_EDGE, cells["g3"])
	cells["f3"].SetChildNode(LEFTBOTTON_EDGE, cells["f2"])
	cells["f3"].SetChildNode(LEFTUPPER_EDGE, cells["e2"])

	cells["f4"].SetChildNode(UPPER_EDGE, cells["e4"])
	cells["f4"].SetChildNode(RIGHTUPPER_EDGE, cells["f5"])
	cells["f4"].SetChildNode(RIGHTBOTTON_EDGE, cells["g5"])
	cells["f4"].SetChildNode(BOTTON_EDGE, cells["g4"])
	cells["f4"].SetChildNode(LEFTBOTTON_EDGE, cells["f3"])
	cells["f4"].SetChildNode(LEFTUPPER_EDGE, cells["e3"])

	cells["f5"].SetChildNode(UPPER_EDGE, cells["e5"])
	cells["f5"].SetChildNode(BOTTON_EDGE, cells["g5"])
	cells["f5"].SetChildNode(LEFTBOTTON_EDGE, cells["f4"])
	cells["f5"].SetChildNode(LEFTUPPER_EDGE, cells["e4"])

	cells["g1"].SetChildNode(UPPER_EDGE, cells["f1"])
	cells["g1"].SetChildNode(RIGHTUPPER_EDGE, cells["g2"])
	cells["g1"].SetChildNode(RIGHTBOTTON_EDGE, cells["h2"])
	cells["g1"].SetChildNode(BOTTON_EDGE, cells["h1"])

	cells["g2"].SetChildNode(UPPER_EDGE, cells["f2"])
	cells["g2"].SetChildNode(RIGHTUPPER_EDGE, cells["g3"])
	cells["g2"].SetChildNode(RIGHTBOTTON_EDGE, cells["h3"])
	cells["g2"].SetChildNode(BOTTON_EDGE, cells["h2"])
	cells["g2"].SetChildNode(LEFTBOTTON_EDGE, cells["g1"])
	cells["g2"].SetChildNode(LEFTUPPER_EDGE, cells["f1"])

	cells["g3"].SetChildNode(UPPER_EDGE, cells["f3"])
	cells["g3"].SetChildNode(RIGHTUPPER_EDGE, cells["g4"])
	cells["g3"].SetChildNode(RIGHTBOTTON_EDGE, cells["h4"])
	cells["g3"].SetChildNode(BOTTON_EDGE, cells["h3"])
	cells["g3"].SetChildNode(LEFTBOTTON_EDGE, cells["g2"])
	cells["g3"].SetChildNode(LEFTUPPER_EDGE, cells["f2"])

	cells["g4"].SetChildNode(UPPER_EDGE, cells["f4"])
	cells["g4"].SetChildNode(RIGHTUPPER_EDGE, cells["g5"])
	cells["g4"].SetChildNode(RIGHTBOTTON_EDGE, cells["h5"])
	cells["g4"].SetChildNode(BOTTON_EDGE, cells["h4"])
	cells["g4"].SetChildNode(LEFTBOTTON_EDGE, cells["g3"])
	cells["g4"].SetChildNode(LEFTUPPER_EDGE, cells["f3"])

	cells["g5"].SetChildNode(UPPER_EDGE, cells["f5"])
	cells["g5"].SetChildNode(BOTTON_EDGE, cells["h5"])
	cells["g5"].SetChildNode(LEFTBOTTON_EDGE, cells["g4"])
	cells["g5"].SetChildNode(LEFTUPPER_EDGE, cells["f4"])

	cells["h1"].SetChildNode(UPPER_EDGE, cells["g1"])
	cells["h1"].SetChildNode(RIGHTUPPER_EDGE, cells["h2"])
	cells["h1"].SetChildNode(RIGHTBOTTON_EDGE, cells["i2"])
	cells["h1"].SetChildNode(BOTTON_EDGE, cells["i1"])

	cells["h2"].SetChildNode(UPPER_EDGE, cells["g2"])
	cells["h2"].SetChildNode(RIGHTUPPER_EDGE, cells["h3"])
	cells["h2"].SetChildNode(RIGHTBOTTON_EDGE, cells["i3"])
	cells["h2"].SetChildNode(BOTTON_EDGE, cells["i2"])
	cells["h2"].SetChildNode(LEFTBOTTON_EDGE, cells["h1"])
	cells["h2"].SetChildNode(LEFTUPPER_EDGE, cells["g1"])

	cells["h3"].SetChildNode(UPPER_EDGE, cells["g3"])
	cells["h3"].SetChildNode(RIGHTUPPER_EDGE, cells["h4"])
	cells["h3"].SetChildNode(RIGHTBOTTON_EDGE, cells["i4"])
	cells["h3"].SetChildNode(BOTTON_EDGE, cells["i3"])
	cells["h3"].SetChildNode(LEFTBOTTON_EDGE, cells["h2"])
	cells["h3"].SetChildNode(LEFTUPPER_EDGE, cells["g2"])

	cells["h4"].SetChildNode(UPPER_EDGE, cells["g4"])
	cells["h4"].SetChildNode(RIGHTUPPER_EDGE, cells["h5"])
	cells["h4"].SetChildNode(RIGHTBOTTON_EDGE, cells["i5"])
	cells["h4"].SetChildNode(BOTTON_EDGE, cells["i4"])
	cells["h4"].SetChildNode(LEFTBOTTON_EDGE, cells["h3"])
	cells["h4"].SetChildNode(LEFTUPPER_EDGE, cells["g3"])

	cells["h5"].SetChildNode(UPPER_EDGE, cells["g5"])
	cells["h5"].SetChildNode(BOTTON_EDGE, cells["i5"])
	cells["h5"].SetChildNode(LEFTBOTTON_EDGE, cells["h4"])
	cells["h5"].SetChildNode(LEFTUPPER_EDGE, cells["g4"])

	cells["i1"].SetChildNode(UPPER_EDGE, cells["h1"])
	cells["i1"].SetChildNode(RIGHTUPPER_EDGE, cells["i2"])
	cells["i1"].SetChildNode(RIGHTBOTTON_EDGE, cells["j2"])

	cells["i2"].SetChildNode(UPPER_EDGE, cells["h2"])
	cells["i2"].SetChildNode(RIGHTUPPER_EDGE, cells["i3"])
	cells["i2"].SetChildNode(RIGHTBOTTON_EDGE, cells["j3"])
	cells["i2"].SetChildNode(BOTTON_EDGE, cells["j2"])
	cells["i2"].SetChildNode(LEFTBOTTON_EDGE, cells["i1"])
	cells["i2"].SetChildNode(LEFTUPPER_EDGE, cells["h1"])

	cells["i3"].SetChildNode(UPPER_EDGE, cells["h3"])
	cells["i3"].SetChildNode(RIGHTUPPER_EDGE, cells["i4"])
	cells["i3"].SetChildNode(RIGHTBOTTON_EDGE, cells["j4"])
	cells["i3"].SetChildNode(BOTTON_EDGE, cells["j3"])
	cells["i3"].SetChildNode(LEFTBOTTON_EDGE, cells["i2"])
	cells["i3"].SetChildNode(LEFTUPPER_EDGE, cells["h2"])

	cells["i4"].SetChildNode(UPPER_EDGE, cells["h4"])
	cells["i4"].SetChildNode(RIGHTUPPER_EDGE, cells["i5"])
	cells["i4"].SetChildNode(RIGHTBOTTON_EDGE, cells["j5"])
	cells["i4"].SetChildNode(BOTTON_EDGE, cells["j4"])
	cells["i4"].SetChildNode(LEFTBOTTON_EDGE, cells["i3"])
	cells["i4"].SetChildNode(LEFTUPPER_EDGE, cells["h3"])

	cells["i5"].SetChildNode(UPPER_EDGE, cells["h5"])
	cells["i5"].SetChildNode(BOTTON_EDGE, cells["j5"])
	cells["i5"].SetChildNode(LEFTBOTTON_EDGE, cells["i4"])
	cells["i5"].SetChildNode(LEFTUPPER_EDGE, cells["h4"])

	cells["j2"].SetChildNode(UPPER_EDGE, cells["i2"])
	cells["j2"].SetChildNode(RIGHTUPPER_EDGE, cells["j3"])
	cells["j2"].SetChildNode(RIGHTBOTTON_EDGE, cells["k3"])
	cells["j2"].SetChildNode(LEFTUPPER_EDGE, cells["i1"])

	cells["j3"].SetChildNode(UPPER_EDGE, cells["i3"])
	cells["j3"].SetChildNode(RIGHTUPPER_EDGE, cells["j4"])
	cells["j3"].SetChildNode(RIGHTBOTTON_EDGE, cells["k4"])
	cells["j3"].SetChildNode(BOTTON_EDGE, cells["k3"])
	cells["j3"].SetChildNode(LEFTBOTTON_EDGE, cells["j2"])
	cells["j3"].SetChildNode(LEFTUPPER_EDGE, cells["i2"])

	cells["j4"].SetChildNode(UPPER_EDGE, cells["i4"])
	cells["j4"].SetChildNode(RIGHTUPPER_EDGE, cells["j5"])
	cells["j4"].SetChildNode(RIGHTBOTTON_EDGE, cells["k5"])
	cells["j4"].SetChildNode(BOTTON_EDGE, cells["k4"])
	cells["j4"].SetChildNode(LEFTBOTTON_EDGE, cells["j3"])
	cells["j4"].SetChildNode(LEFTUPPER_EDGE, cells["i3"])

	cells["j5"].SetChildNode(UPPER_EDGE, cells["i5"])
	cells["j5"].SetChildNode(BOTTON_EDGE, cells["k5"])
	cells["j5"].SetChildNode(LEFTBOTTON_EDGE, cells["j4"])
	cells["j5"].SetChildNode(LEFTUPPER_EDGE, cells["i4"])

	cells["k3"].SetChildNode(UPPER_EDGE, cells["j3"])
	cells["k3"].SetChildNode(RIGHTUPPER_EDGE, cells["k4"])
	cells["k3"].SetChildNode(LEFTUPPER_EDGE, cells["j2"])

	cells["k4"].SetChildNode(UPPER_EDGE, cells["j4"])
	cells["k4"].SetChildNode(RIGHTUPPER_EDGE, cells["k5"])
	cells["k4"].SetChildNode(LEFTBOTTON_EDGE, cells["k3"])
	cells["k4"].SetChildNode(LEFTUPPER_EDGE, cells["j3"])

	cells["k5"].SetChildNode(UPPER_EDGE, cells["j5"])
	cells["k5"].SetChildNode(LEFTBOTTON_EDGE, cells["k4"])
	cells["k5"].SetChildNode(LEFTUPPER_EDGE, cells["j4"])

}
